image: registry.gitlab.inria.fr/navarop/julia:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - julia -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'
  tags:
    - ci.inria.fr


test_linux:
  stage: test  
  tags:
    - ci.inria.fr
  script: 
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    - julia --project=test/coverage test/coverage/coverage-summary.jl
  coverage: '/Total: (\d+\.\d+)% of lines covered/'    # Run tests 
  

 
# # windows tests
windows:
  stage: test
  tags:
    - win
  script:
    - whoami
    - echo $Env:PATH
    - Start-Service ssh-agent
    - ssh -T git@gitlab.inria.fr
    - julia --version
    - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.update()'   # Install dependencies
    - julia -e 'using Pkg; Pkg.status()'  # Install dependencies
    - julia --project=. test/runtests.jl"  # Run tests 

# macOS tests
# macos:
#   stage: test
#   tags:
#     - macos-catalina
#   script:
#     - whoami
#     - . /Users/ci/.bashrc
#     - ssh -T git@gitlab.inria.fr
#     - julia --version
#     - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.update()'   # Install dependencies
#     - julia --project=. test/runtests.jl          # Run tests 
   
pages:
  image: julia:1.11
  tags:
    - ci.inria.fr
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y git libpcre2-8-0
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - export LD_LIBRARY_PATH=/usr/local/julia/lib/julia:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  script:
    - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    - julia --project=docs --color=yes docs/make.jl
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
  - main