site_name: PACE
site_dir: 'public/'
docs_dir: 'docs'

site_url: https://ckatsama.gitlabpages.inria.fr/mpfi.jl

nav:
  - index.md

theme:
  name: 'material'
  features:
    - content.code.copy # code copy button

  # Enable dask/light mode
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# enable codeblocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

